# Generated by Django 5.0.1 on 2025-07-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (USD)')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Asosiy rasm')),
                ('video_url', models.URLField(blank=True, help_text='YouTube video linki', null=True, verbose_name='Video URL')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likelar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya qilingan')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Omborda bor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Brend')),
                ('car_models', models.ManyToManyField(blank=True, to='brands.carmodel', verbose_name='Avtomobil modellari')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
