# Generated by Django 5.0.1 on 2025-07-19 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('payment_pending', "To'lov kutilmoqda"), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('shipped', "Jo'natildi"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi'), ('payment_rejected', "To'lov rad etildi")], default='pending', max_length=20, verbose_name='Holati')),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa (USD)')),
                ('total_amount_som', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy summa (UZS)')),
                ('usd_rate_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ishlatilgan dollar kursi')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name="To'lov cheki")),
                ('payment_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name="To'lov qilingan karta")),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Yetkazish manzili')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yetkazish telefoni')),
                ('oferta_agreed', models.BooleanField(default=False, verbose_name='Oferta bilan tanishdi')),
                ('oferta_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='Oferta vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (USD)')),
                ('price_som', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi (UZS)')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='order_products/', verbose_name='Mahsulot rasmi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('payment_pending', "To'lov kutilmoqda"), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('shipped', "Jo'natildi"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi'), ('payment_rejected', "To'lov rad etildi")], max_length=20, verbose_name='Holat')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
