# Generated by Django 5.0.1 on 2025-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_som',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Narxi (UZS)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narxi (USD)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mahsulot nomi'),
        ),
    ]
