# Generated by Django 5.0.1 on 2025-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_price_som_alter_orderitem_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Admin izohlar'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Admin izohlar'),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Admin izohlar'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='comment_en',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='comment_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='comment_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
    ]
