services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  # Telegram Bot service
  bot:
    build: .
    command: python manage.py start_bot
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data_dev: