# Generated by Django 5.0.1 on 2025-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
