# Generated by Django 5.0.1 on 2025-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_name_en',
            field=models.CharField(default='Avtokontinent.uz', max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_name_ru',
            field=models.CharField(default='Avtokontinent.uz', max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_name_uz',
            field=models.CharField(default='Avtokontinent.uz', max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
    ]
