# Generated by Django 5.0.1 on 2025-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Sharh'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Sharh'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Sharh'),
        ),
    ]
