# Generated by Django 5.0.1 on 2025-07-19 11:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vaqtinchalik kod',
                'verbose_name_plural': 'Vaqtinchalik kodlar',
            },
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon')),
                ('code', models.CharField(max_length=4)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('temp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_auth.tempcode', verbose_name='Vaqtinchalik kod')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi kodi',
                'verbose_name_plural': 'Foydalanuvchi kodlari',
            },
        ),
    ]
