# Generated by Django 5.0.1 on 2025-07-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vaqtinchalik kod', 'verbose_name_plural': 'Vaqtinchalik kodlar'},
        ),
        migrations.AlterModelOptions(
            name='usercode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi kodi', 'verbose_name_plural': 'Foydalanuvchi kodlari'},
        ),
        migrations.AlterField(
            model_name='usercode',
            name='temp_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_auth.tempcode', verbose_name='Vaqtinchalik kod'),
        ),
    ]
