# Generated by Django 5.0.1 on 2025-07-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_auth', '0002_alter_tempcode_options_alter_usercode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercode',
            name='temp_code',
        ),
        migrations.AlterField(
            model_name='usercode',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='TempCode',
        ),
    ]
